# Generated by Django 3.2.7 on 2021-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runicheskiy_Vosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runa', models.CharField(max_length=15)),
            ],
        ),
    ]
