# Generated by Django 3.2.7 on 2021-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runicheskiy_vosk',
            name='runa',
            field=models.CharField(choices=[('fh', 'fehu'), ('uz', 'uruz')], default='fh', max_length=15),
        ),
    ]
