# Generated by Django 3.2.7 on 2021-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0002_alter_runicheskiy_vosk_runa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunicheskiyVosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runa_1', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_2', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_3', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_4', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_5', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_6', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
                ('runa_7', models.CharField(choices=[('fehu', 'fehu'), ('uruz', 'uruz')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Runicheskiy_Vosk',
        ),
    ]
