# Generated by Django 3.2.7 on 2021-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0003_auto_20210918_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_1',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_2',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_3',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_4',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_5',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_6',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_7',
            field=models.CharField(choices=[('fehu', 'Fehu'), ('uruz', 'Uruz')], max_length=15),
        ),
    ]
