# Generated by Django 3.2.7 on 2021-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0004_auto_20210920_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_1',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_2',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_3',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_4',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_5',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_6',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
        migrations.AlterField(
            model_name='runicheskiyvosk',
            name='runa_7',
            field=models.CharField(choices=[('fehu', 'Феху'), ('uruz', 'Уруз'), ('thurisaz', 'Турисаз'), ('ansuz', 'Ансуз'), ('raido', 'Райдо'), ('kaunaz', 'Кеназ'), ('gebo', 'Гебо'), ('wunjo', 'Вуньо'), ('hagalaz', 'Хагалаз'), ('nauthiz', 'Наутиз'), ('isa', 'Иса'), ('jera', 'Йера'), ('eihwaz', 'Эйваз'), ('pertho', 'Перт'), ('algiz', 'Альгиз'), ('soulo', 'Соулу'), ('teiwaz', 'Тейваз'), ('berkana', 'Беркана'), ('ehwaz', 'Эваз'), ('mannaz', 'Манназ'), ('laguz', 'Лагуз'), ('inguz', 'Ингуз'), ('dagaz', 'Дагаз'), ('odal', 'Одал')], max_length=15),
        ),
    ]
