# Generated by Django 3.2.7 on 2021-09-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0005_auto_20210920_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersKeys',
            fields=[
                ('runa_1runa_7', models.CharField(max_length=20)),
                ('runa_1runa_6', models.CharField(max_length=20)),
                ('runa_1runa_5', models.CharField(max_length=20)),
                ('runa_1runa_4', models.CharField(max_length=20)),
                ('runa_1runa_3', models.CharField(max_length=20)),
                ('runa_1runa_2', models.CharField(max_length=20)),
                ('runa_2runa_7', models.CharField(max_length=20)),
                ('runa_2runa_6', models.CharField(max_length=20)),
                ('runa_2runa_5', models.CharField(max_length=20)),
                ('runa_2runa_4', models.CharField(max_length=20)),
                ('runa_2runa_3', models.CharField(max_length=20)),
                ('runa_3runa_7', models.CharField(max_length=20)),
                ('runa_3runa_6', models.CharField(max_length=20)),
                ('runa_3runa_5', models.CharField(max_length=20)),
                ('runa_3runa_4', models.CharField(max_length=20)),
                ('runa_4runa_7', models.CharField(max_length=20)),
                ('runa_4runa_6', models.CharField(max_length=20)),
                ('runa_4runa_5', models.CharField(max_length=20)),
                ('runa_5runa_7', models.CharField(max_length=20)),
                ('runa_5runa_6', models.CharField(max_length=20)),
                ('runa_6runa_7', models.CharField(max_length=20)),
                ('runa_7runa_1', models.CharField(max_length=20)),
                ('runa_6runa_1', models.CharField(max_length=20)),
                ('runa_5runa_1', models.CharField(max_length=20)),
                ('runa_4runa_1', models.CharField(max_length=20)),
                ('runa_3runa_1', models.CharField(max_length=20)),
                ('runa_2runa_1', models.CharField(max_length=20)),
                ('runa_7runa_2', models.CharField(max_length=20)),
                ('runa_6runa_2', models.CharField(max_length=20)),
                ('runa_5runa_2', models.CharField(max_length=20)),
                ('runa_4runa_2', models.CharField(max_length=20)),
                ('runa_3runa_2', models.CharField(max_length=20)),
                ('runa_7runa_3', models.CharField(max_length=20)),
                ('runa_6runa_3', models.CharField(max_length=20)),
                ('runa_5runa_3', models.CharField(max_length=20)),
                ('runa_4runa_3', models.CharField(max_length=20)),
                ('runa_7runa_4', models.CharField(max_length=20)),
                ('runa_6runa_4', models.CharField(max_length=20)),
                ('runa_5runa_4', models.CharField(max_length=20)),
                ('runa_7runa_5', models.CharField(max_length=20)),
                ('runa_6runa_5', models.CharField(max_length=20)),
                ('runa_7runa_6', models.CharField(max_length=20)),
                ('rv_answers_keys', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RV.runicheskiyvosk')),
            ],
        ),
    ]
