# Generated by Django 3.2.7 on 2021-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0006_answerskeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManticKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_keys', models.CharField(max_length=20)),
                ('value_name', models.CharField(max_length=20)),
                ('value_mantic', models.CharField(max_length=200)),
                ('value_protection', models.CharField(max_length=200)),
                ('mantic_answers', models.ManyToManyField(to='RV.AnswersKeys')),
            ],
        ),
    ]
