# Generated by Django 3.2.7 on 2021-10-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0007_mantickeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantickeys',
            name='mantic_answers',
            field=models.ManyToManyField(to='RV.RunicheskiyVosk'),
        ),
    ]
