# Generated by Django 3.2.7 on 2021-10-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0008_alter_mantickeys_mantic_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswersKeys',
        ),
    ]
